version: "3.8"
services:
  postgres-test:
    image: postgres:15
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: myapp_test
    ports:
      - "54321:5432"
